kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: RLRnFeigQfO1kyDTW48CtTGthTMb6Qzuk+E4r4GuKIc=
      - identity: {}
